require 'active_support'
require 'active_support/core_ext/object/blank'
require 'active_support/core_ext/hash/keys'
require 'active_support/core_ext/hash/indifferent_access'
require 'active_support/core_ext/kernel/reporting'
require_relative 'dependency_analyser/version'
require_relative 'dependency_analyser/dependency_analyser'
require_relative 'dependency_analyser/cli'
include DependencyAnalyser
